#!/usr/bin/env python
#
#  List backups that should be run at the current time on the current server.

import sys
sys.path.append('/usr/local/lib/tummy-backup/lib')
from psycopgwrap import Database as db
import tbsupp
db.connect()


config = db.query('SELECT * FROM config')[0]
backupserver = tbsupp.getThisBackupServer(db)
for host in db.query(
        "SELECT hostname FROM hosts "
        "WHERE backupserver_id = %s AND "
        "EXTRACT('hour' FROM window_start_time) "
        "= EXTRACT('hour' from current_time) "
        "AND (SELECT COUNT(*) FROM backups WHERE backup_pid IS NOT NULL "
        "    AND backups.backupserver_id = hosts.backupserver_id "
        "    AND backups.host_id = hosts.id) < 1", backupserver['id']):
    print host[0]
