#!/usr/bin/env python
#
#  Look for backups that can be removed
#  NOTE: This should run on every backup server

import sys, os
sys.path.append('/usr/local/lib/tummy-backup/lib')

import tbsupp
from psycopgwrap import Database as db
db.connect()


#  backups that are no longer running
tbsupp.clearDeadBackups(db)
