#!/usr/bin/env python
#
#  Print to stdout a report of server name and MB used.

import sys, os, time
sys.path.append('/usr/local/lib/tummy-backup/lib')
os.environ['PATH'] = (os.environ['PATH'] +
		':/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin')

from psycopgwrap import Database as db
db.connect()


############################################
now = time.time()
for host in db.query("SELECT * FROM hosts "
		"WHERE active = 't' ORDER BY hostname;"):
	#  new hsots have no space used
	if (host['space_used_snapshots'] == None or
			host['space_used_dataset'] == None):
		continue

	print '%s %d' % ( host['hostname'], (host['space_used_snapshots']
			+ host['space_used_dataset']) / 1024 / 1024 )
